apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: ${{ values.description }}
spec:
  type: service
  lifecycle: production
  owner: group:guest