---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
  title: Tech4Impact Team
  links:
    - url: https://www.linkedin.com/in/pablo-fernandez-3985578b
      title: Pablo
    - url: https://www.linkedin.com/in/fjbalsamo
      title: Franco
spec:
  type: team
  children: []
